services:
  users:
    name: users
    timeout: "10s"
    target: http://localhost:8000/api
    middlewares:
      - auth_jwt
      - cors
      - logger
    rate_limits:
      - type: bucket
        rate: 20
        burst: 1
      - type: window
        limit: 60
        interval: "1m" #60 request in 1min, if empty default -> "1m"
    circuit_breaker:
      failure_threshold: 2 #falhas antes abrir
      retry_timeout: "30s"
      before:
        - logger
    retry:
      attempts: 3
      backoff: exponential
      delay: "400ms"

    
